services:
  ip-extractor:
    build: 
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./data/access.log:/app/data/access.log
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE_NAME=ip_extraction
      - COLLECTION_NAME=private_ips

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ip_extraction

volumes:
  mongodb_data: